fixing the issue regarding serialization and deserialization of neste…
diem/bcs pull request #5
Opened 2022-11-03 11:15 UTC by vikalpacn

…d enums would not match.

2022-11-03 11:19 UTC, vikalpacn commented
/canary

2022-11-10 06:23 UTC, vikalpacn commented
/canary

2022-11-14 15:16 UTC, KoushikGavini approved these changes

2022-11-14 22:45 UTC, KoushikGavini requested changes
Lets fix Lint check

2022-11-15 12:14 UTC, vikalpacn commented
There was a small bug where the serialization and deserialization of nested 
enums would not match, So a fork created of diem/bcs in the Zefchain org, applied the fix, and 
then released v0.1.4 of bcs to crates.io

The fixes done in Zefchain branch, are incorporated in forked repo of Diem bcs and then merged with diem/diem.

1. First step is to apply the fixes in diem bcs version 0.1.3 regarding the matching of serialization and de-serialization
 of Nested enums and updating it to version 0.1.4.

2. Then, building diem bcs version 0.1.4 and performing unit testing for fn test_recursion_limit() :
  - cargo test --package bcs --test serde -- test_recursion_limit --exact --nocapture
   
3. After successful build and testing, referring diem bcs version 0.1.4 to diem code base.

4. To refer, first making changes in bcs of cargo.toml file of a single module (Applying path of diem bcs- )
     * then,   
     1. Build- cargo build
     2. Test- cargo test -p "Name of a perticular module"
	 
5.After succesfull build of a single module, futher applying the changes in all the modules by giving address of diem bcs in cargo.toml file.

6. Then, 
 1. cargo build diem-  cargo build
 2. Smoke test- cargo x test --package smoke-test -- --test-threads 1
 3. integration test- cargo xtest -p jsonrpc-integration-tests

2022-11-15 17:08 UTC, KoushikGavini approved these changes

2022-11-16 06:04 UTC, vikalpacn commented
/canary

2022-11-21 06:38 UTC, vikalpacn commented
/canary

2022-11-22 06:36 UTC, merged